# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
    mod_version = 2.12.13
    archives_base_name = Apoli-Legacy

# Dependencies
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
    pal_version=1.16.0
    aea_version=2.2.4+26.1