# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
    mod_version = 2.9.0
    maven_group = com.github.apace100
    archives_base_name = Apoli-1.20.1

# Dependencies
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
    cca_version=5.2.1
    pal_version=1.8.0
    clothconfig_version=11.0.99
    aea_version=89b98f4