# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.5

# Mod Properties
    mod_version = 2.12.13
    archives_base_name = Apoli-Legacy
    maven_group = io.github.apace100

# Dependencies
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
    pal_version=1.16.0
    aea_version=2.2.4+26.1
    fabric_version=0.155.3+26.1.2
    cca_version=8.0.1
    calio_version=1.11.4+26.1.2
    clothconfig_version=26.1.154
    modmenu_version=18.0.1
    appleskin_version=mc26.1.2-3.0.10